apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJmcmFuY2FybDc3IiwicGFzc3dvcmQiOiJnaHBfRFBEVXpNOEd0VVZTSFBrUmszbTEyMWJ3bm9wU2l3NDJQR04zIiwiZW1haWwiOiJmcmFuY2VzY28uY2FybHVjY2lAYWNjZW50dXJlLmNvbSIsImF1dGgiOiJabkpoYm1OaGNtdzNOenBuYUhCZlJGQkVWWHBOT0VkMFZWWlRTRkJyVW1zemJURXlNV0ozYm05d1UybDNOREpRUjA0eiJ9fX0=
type: kubernetes.io/dockerconfigjson