apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalhub-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: signalhub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: signalhub
        env: dev
        checks: passed
    spec:
      serviceAccountName: signalhub-serviceaccount
      containers:
        - name: signalhub-container
          image: ghcr.io/francarl77/signalhub:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1.0
          env:
            - name: AWS_REGION_CODE
              value: eu-south-1
            - name: AWS_INTERNAL_QUEUE_NAME
              value: signalhub-sqs
            - name: AWS_SQS_ENDPOINT
              value: https://sqs.eu-south-1.amazonaws.com/248862543363
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: m0mtZ7p2DxoqE8IOqzx9
            - name: DATABASE_HOST
              value: signalhub-rds-db-instance-1.ci5nksqtybl9.eu-south-1.rds.amazonaws.com
            - name: DATABASE_PORT
              value: 5432
            - name: AWS_DYNAMODB_SIGNAL_TABLE
              value: Signal
            - name: AWS_DYNAMODB_INDEX_SIGNAL_COUNTER_TABLE
              value: IndexSignalCounter
            - name: AWS_POD_NAME_MS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
      imagePullSecrets:
        - name: ghcr-login-secret
